# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: canguru
      MONGO_INITDB_ROOT_USERNAME: canguru
      MONGO_INITDB_ROOT_PASSWORD: virus3301
    volumes:
      - mongodbdata:/data/db #execute docker volume create mongodbdata
    ports:
      - 27017:27017
volumes:
  mongodbdata:
    external: true
    
