version: '3.1'

services:  mongo:    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: canguru
      MONGODB_DATABASE: canguru
      MONGO_INITDB_ROOT_USERNAME: canguru
      MONGO_INITDB_ROOT_PASSWORD: "@virus3301"
    volumes:
      [./mongo-volume:/data/db]
    ports:
       [27017:27017]